# Generated by Django 4.0 on 2022-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blazers',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='t_shirts',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
