# Generated by Django 4.0 on 2022-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_blazers_price_alter_shirts_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blazers',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shirts',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sweaters',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='t_shirts',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
